server:
  port: 8061
  servlet:
    context-path: /${spring.application.name}

rocketmq:
  name-server: 120.46.181.75:9876
  producer:
    group: provider
spring:
  # Redis连接配置
  redis:
    host: 120.48.48.87
    port: 6379
    password: 123456
    database: 0
    timeout: 1800000  # 连接超时时间（毫秒）
    lettuce:
      pool:
        max-active: 20   # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 最大阻塞等待时间(负数表示没限制)
        max-idle: 5   #连接池中的最大空闲连接
        min-idle: 0   #连接池中的最小空闲连接
