spring:
  application:
    name: order
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.citycloud.nacostest.order.mapper
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
